language: python
python:
- '2.7'
cache: pip
services:
- postgresql
install:
- ./scripts/bootstrap.sh
- pip install coveralls
script:
# - eval $INTEGRITY_SCRIPT
- sudo apt-get install ghostscript
- sudo mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml.off
- ./scripts/run_tests.sh
after_success:
- coveralls
deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh preview
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh development
    on:
      branch: test-deploy
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh live
    on:
      tags: true
