language: python
python:
- '2.7'
cache: pip
services:
- postgresql
env:
- DATABASE_URL_development=postgresql://localhost/newacropolis_db
install:
- ./bootstrap.sh
script:
- ./run_tests.sh
addons:
  ssh_known_hosts: 35.197.111.255
before_deploy:
- openssl aes-256-cbc -K $encrypted_cc02c135ea1a_key -iv $encrypted_cc02c135ea1a_iv
  -in na_rsa.enc -out na_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 na_rsa
- ssh-add na_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
before_install:
