language: python
python:
- '2.7'
cache: pip
services:
- postgresql
install:
- ./bootstrap.sh
script:
- ./run_tests.sh
before_deploy:
- openssl aes-256-cbc -K $encrypted_cc02c135ea1a_key -iv $encrypted_cc02c135ea1a_iv
  -in travis_rsa.enc -out travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add travis_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh preview
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh development
    on:
      branch: test-deploy
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh live
    on:
      branch: live-deploy
