"""empty message

Revision ID: 0018 null event_dates.venue_id
Revises: 0017 drop speaker_id from events
Create Date: 2018-11-04 23:45:40.295527

"""

# revision identifiers, used by Alembic.
revision = '0018 null event_dates.venue_id'
down_revision = '0017 drop speaker_id from events'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_dates', 'venue_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_dates', 'venue_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
