"""empty message

Revision ID: 0020 add venue to events
Revises: 0019 add duration to events
Create Date: 2018-11-05 00:07:13.360790

"""

# revision identifiers, used by Alembic.
revision = '0020 add venue to events'
down_revision = '0019 add duration to events'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('venue_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'venue_id')
    # ### end Alembic commands ###
