"""empty message

Revision ID: 0034 add send_after to emails
Revises: 0033 drop tickets.old_event_id
Create Date: 2019-10-09 16:30:23.342044

"""

# revision identifiers, used by Alembic.
revision = '0034 add send_after to emails'
down_revision = '0033 drop tickets.old_event_id'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('send_after', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'send_after')
    # ### end Alembic commands ###
