"""empty message

Revision ID: 0036 add magazines
Revises: 0035 add basic email template
Create Date: 2019-11-22 00:01:15.333826

"""

# revision identifiers, used by Alembic.
revision = '0036 add magazines'
down_revision = '0035 add basic email template'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magazines',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('old_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('old_filename'),
    sa.UniqueConstraint('old_id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magazines')
    # ### end Alembic commands ###
