"""empty message

Revision ID: 0037 add magazine_id to emails
Revises: 0036 add magazines
Create Date: 2020-01-30 00:09:30.416015

"""

# revision identifiers, used by Alembic.
revision = '0037 add magazine_id to emails'
down_revision = '0036 add magazines'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('magazine_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'emails', 'magazines', ['magazine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'magazine_id')
    # ### end Alembic commands ###
