"""empty message

Revision ID: 0039 add subject to emails
Revises: 0038 add topics to magazines
Create Date: 2020-02-16 01:47:26.969337

"""

# revision identifiers, used by Alembic.
revision = '0039 add subject to emails'
down_revision = '0038 add topics to magazines'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'subject')
    # ### end Alembic commands ###
