"""empty message

Revision ID: 0040 add email providers
Revises: 0039 add subject to emails
Create Date: 2020-06-18 01:38:30.911104

"""

# revision identifiers, used by Alembic.
revision = '0040 add email providers'
down_revision = '0039 add subject to emails'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_providers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('data_struct', sa.String(), nullable=True),
    sa.Column('pos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pos')
    )
    op.add_column(u'email_to_member', sa.Column('emailed_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'email_to_member', 'emailed_by')
    op.drop_table('email_providers')
    # ### end Alembic commands ###
