"""empty message

Revision ID: 0042 increase booking_code size
Revises: 0041 update email providers
Create Date: 2020-08-12 15:04:31.869762

"""

# revision identifiers, used by Alembic.
revision = '0042 increase booking_code size'
down_revision = '0041 update email providers'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'booking_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'booking_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
