"""empty message
Revision ID: 0043 add image_filename articles
Revises: 0042 increase booking_code size
Create Date: 2020-09-20 22:35:05.686663

"""

# revision identifiers, used by Alembic.
revision = '0043 add image_filename articles'
down_revision = '0042 increase booking_code size'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'image_filename')
    # ### end Alembic commands ###
