"""empty message

Revision ID: 0049 mod order, add order_errors
Revises: 0048 add book_to_order
Create Date: 2021-03-06 01:49:37.117621

"""

# revision identifiers, used by Alembic.
revision = '0049 mod order, add order_errors'
down_revision = '0048 add book_to_order'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order_errors',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('error', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_country', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_country_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_postal_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_street', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_balance', sa.Numeric(precision=2), nullable=True))
    op.add_column('orders', sa.Column('delivery_status', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('delivery_zone', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_zone')
    op.drop_column('orders', 'delivery_status')
    op.drop_column('orders', 'delivery_diff')
    op.drop_column('orders', 'address_street')
    op.drop_column('orders', 'address_state')
    op.drop_column('orders', 'address_postal_code')
    op.drop_column('orders', 'address_country_code')
    op.drop_column('orders', 'address_country')
    op.drop_column('orders', 'address_city')
    op.drop_table('order_errors')
    # ### end Alembic commands ###
