"""empty message

Revision ID: 0049 update orders add & del
Revises: 0048 add book_to_order
Create Date: 2020-12-06 01:21:11.834888

"""

# revision identifiers, used by Alembic.
revision = '0049 update orders add & del'
down_revision = '0048 add book_to_order'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_country', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_country_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_postal_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_street', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_zone', sa.String(length=5), nullable=True))
    op.add_column('orders', sa.Column('delivery_zone_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_zone_confirmed')
    op.drop_column('orders', 'delivery_zone')
    op.drop_column('orders', 'address_street')
    op.drop_column('orders', 'address_state')
    op.drop_column('orders', 'address_postal_code')
    op.drop_column('orders', 'address_country_code')
    op.drop_column('orders', 'address_country')
    op.drop_column('orders', 'address_city')
    # ### end Alembic commands ###
