"""empty message

Revision ID: 0050 add linked_txn_id
Revises: 0049 mod order, add order_errors
Create Date: 2021-04-19 17:30:24.454878

"""

# revision identifiers, used by Alembic.
revision = '0050 add linked_txn_id'
down_revision = '0049 mod order, add order_errors'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('linked_txn_id', sa.String(), nullable=True))
    # op.add_column('orders', sa.Column('delivery_balance', sa.Numeric(scale=2), nullable=True))
    op.alter_column(
        u'orders', 'delivery_balance',
        existing_type=sa.Numeric(precision=2),
        type_=sa.Numeric(scale=2),
        existing_nullable=True
    )
    op.alter_column(
        u'orders', 'payment_total',
        existing_type=sa.Numeric(precision=2),
        type_=sa.Numeric(scale=2),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'linked_txn_id')
    op.alter_column(
        u'orders', 'delivery_balance',
        existing_type=sa.Numeric(scale=2),
        type_=sa.Numeric(precision=2),
        existing_nullable=True
    )
    op.alter_column(
        u'orders', 'payment_total',
        existing_type=sa.Numeric(scale=2),
        type_=sa.Numeric(precision=2),
        existing_nullable=True
    )
    # ### end Alembic commands ###
