"""empty message

Revision ID: 0051 add delivery_sent, notes
Revises: 0050 add linked_txn_id
Create Date: 2021-08-12 16:56:45.583318

"""

# revision identifiers, used by Alembic.
revision = '0051 add delivery_sent, notes'
down_revision = '0050 add linked_txn_id'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_sent', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_sent')
    op.drop_column('orders', 'notes')
    # ### end Alembic commands ###
