"""empty message

Revision ID: 0052 add refund_issued
Revises: 0052 add remote login
Create Date: 2021-08-31 01:20:46.059442

"""

# revision identifiers, used by Alembic.
revision = '0052 add refund_issued'
down_revision = '0052 add remote login'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('refund_issued', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'refund_issued')
    # ### end Alembic commands ###
