"""empty message

Revision ID: 0054 add reserved_places
Revises: 0052 add refund_issued
Create Date: 2021-09-06 00:31:22.285217

"""

# revision identifiers, used by Alembic.
revision = '0054 add reserved_places'
down_revision = '0052 add refund_issued'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserved_places',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('eventdate_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eventdate_id'], ['event_dates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserved_places')
    # ### end Alembic commands ###
