"""empty message

Revision ID: 0059 add show_banner_text
Revises: 0058 set all has_banner_text
Create Date: 2021-10-04 00:10:14.535185

"""

# revision identifiers, used by Alembic.
revision = '0059 add show_banner_text'
down_revision = '0058 set all has_banner_text'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events',
      sa.Column(
        'show_banner_text',
        sa.Boolean(),
        nullable=True,
        server_default="True"
      )
    )
    op.drop_column('events', 'has_banner_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('has_banner_text', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('events', 'show_banner_text')
    # ### end Alembic commands ###
