"""empty message

Revision ID: 0062 add magazine tags
Revises: 0061 orders txn_id unique
Create Date: 2022-01-19 00:01:00.309547

"""

# revision identifiers, used by Alembic.
revision = '0062 add magazine tags'
down_revision = '0061 orders txn_id unique'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'tags')
    # ### end Alembic commands ###
