"""empty message

Revision ID: 0063 add monthly_limit
Revises: 0062 add magazine tags
Create Date: 2022-01-30 02:14:47.771456

"""

# revision identifiers, used by Alembic.
revision = '0063 add monthly_limit'
down_revision = '0062 add magazine tags'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_providers', sa.Column('monthly_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_providers', 'monthly_limit')
    # ### end Alembic commands ###
