"""empty message

Revision ID: 0064 add minute_limit
Revises: 0063 add monthly_limit
Create Date: 2022-02-02 01:28:42.543617

"""

# revision identifiers, used by Alembic.
revision = '0064 add minute_limit'
down_revision = '0063 add monthly_limit'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_providers', sa.Column('minute_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_providers', 'minute_limit')
    # ### end Alembic commands ###
