"""empty message

Revision ID: 0065 add auth_type
Revises: 0064 add minute_limit
Create Date: 2022-02-05 00:26:35.246318

"""

# revision identifiers, used by Alembic.
revision = '0065 add auth_type'
down_revision = '0064 add minute_limit'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_providers', sa.Column('auth_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_providers', 'auth_type')
    # ### end Alembic commands ###
