"""empty message

Revision ID: 0067 add is_giftaid
Revises: 0066 add is_donation
Create Date: 2022-02-26 14:12:52.226540

"""

# revision identifiers, used by Alembic.
revision = '0067 add is_giftaid'
down_revision = '0066 add is_donation'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_giftaid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_giftaid')
    # ### end Alembic commands ###
