"""empty message

Revision ID: 0068 update articles
Revises: 0067 add is_giftaid
Create Date: 2022-03-06 01:09:49.951152

"""

# revision identifiers, used by Alembic.
revision = '0068 update articles'
down_revision = '0067 add is_giftaid'

from alembic import op
import sqlalchemy as sa

from app.models import ARTICLE_STATES

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_states',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    for state in ARTICLE_STATES:
        op.execute(
            "INSERT INTO article_states (name) VALUES ('{}')".format(state)
        )

    op.add_column('articles', sa.Column('article_state', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('tags', sa.String(), nullable=True))
    op.create_index(op.f('ix_articles_article_state'), 'articles', ['article_state'], unique=False)
    op.create_foreign_key(None, 'articles', 'article_states', ['article_state'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_article_state'), table_name='articles')
    op.drop_column('articles', 'tags')
    op.drop_column('articles', 'article_state')
    op.drop_table('article_states')
    # ### end Alembic commands ###
