"""empty message

Revision ID: 0069 add magazine_id article
Revises: 0068 update articles
Create Date: 2022-10-10 01:10:05.496893

"""

# revision identifiers, used by Alembic.
revision = '0069 add magazine_id article'
down_revision = '0068 update articles'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('magazine_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'articles', 'magazines', ['magazine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'magazine_id')
    # ### end Alembic commands ###
