"""empty message

Revision ID: 0070 add email details to order
Revises: 0069 add magazine_id article
Create Date: 2022-10-30 01:13:55.881762

"""

# revision identifiers, used by Alembic.
revision = '0070 add email details to order'
down_revision = '0069 add magazine_id article'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email_provider_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('orders', sa.Column('email_status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'email_providers', ['email_provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'email_status')
    op.drop_column('orders', 'email_provider_id')
    # ### end Alembic commands ###
