"""empty message

Revision ID: 0072 add email_sent_at orders
Revises: 0071 articles state to approved
Create Date: 2023-04-22 13:45:35.034184

"""

# revision identifiers, used by Alembic.
revision = '0072 add email_sent_at orders'
down_revision = '0071 articles state to approved'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'email_sent_at')
    # ### end Alembic commands ###
