"""empty message

Revision ID: 0072 add source_filename
Revises: 0072 add email_sent_at orders
Create Date: 2023-06-24 01:18:51.849580

"""

# revision identifiers, used by Alembic.
revision = '0072 add source_filename'
down_revision = '0072 add email_sent_at orders'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'source_filename')
    # ### end Alembic commands ###
