"""empty message

Revision ID: 0075 add admin_email_sent_at
Revises: 0074 add shipping_cost
Create Date: 2024-06-12 01:21:04.015963

"""

# revision identifiers, used by Alembic.
revision = '0075 add admin_email_sent_at'
down_revision = '0074 add shipping_cost'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('admin_email_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'admin_email_sent_at')
    # ### end Alembic commands ###
