"""empty message

Revision ID: 0076 add headline to events
Revises: 0075 add admin_email_sent_at
Create Date: 2024-11-13 00:52:25.894499

"""

# revision identifiers, used by Alembic.
revision = '0076 add headline to events'
down_revision = '0075 add admin_email_sent_at'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('headline', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'headline')
    # ### end Alembic commands ###
