"""empty message

Revision ID: 0079 Add email has_reminder
Revises: 0078 Update book price
Create Date: 2026-01-25 01:48:20.851301

"""

# revision identifiers, used by Alembic.
revision = '0079 Add email has_reminder'
down_revision = '0078 Update book price'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_to_member', sa.Column('is_reminder', sa.BOOLEAN(), nullable=False))
    op.add_column('emails', sa.Column('has_reminder', sa.Boolean(), nullable=True))
    # op.drop_constraint('email_to_member_pk', 'email_to_member', type_='primary')
    # op.execute("select indexname from pg_indexes  where tablename = 'email_to_member'")

    op.drop_constraint('email_to_member_pk', 'email_to_member', type_='primary')
    # op.execute("ALTER TABLE email_to_member DROP CONSTRAINT email_to_member_pk")
    op.create_primary_key("email_to_member_pk", "email_to_member", ('email_id', 'member_id', 'is_reminder'))

    # ### end Alembic commands ###

    # select * from pg_indexes  where tablename = 'email_to_member'

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'has_reminder')
    op.drop_column('email_to_member', 'is_reminder')
    # op.drop_constraint('email_to_member_pk', 'email_to_member', type_='primary')
    op.create_primary_key("email_to_member_pk", "email_to_member", ('email_id', 'member_id'))
    # ### end Alembic commands ###
