"""empty message

Revision ID: 0079 Add parent_email_id
Revises: 0078 Update book price
Create Date: 2026-01-29 00:51:34.451073

"""

# revision identifiers, used by Alembic.
revision = '0079 Add parent_email_id'
down_revision = '0078 Update book price'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('parent_email_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'emails', 'emails', ['parent_email_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'parent_email_id')
    # ### end Alembic commands ###
