on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: na_api_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      TEST_DATABASE_URI: postgresql://postgres@localhost/na_api_test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
          sudo apt-get install build-essential libpoppler-cpp-dev pkg-config
          sudo apt-get install ghostscript
          sudo mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml.off

          ./scripts/bootstrap.sh
          # pip install coveralls
      - name: Run tests
        run: ./scripts/run_tests.sh
      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
